#!/usr/bin/env python

"""
Testing Code
"""

import subprocess
import os
import sys
import itertools


def main():
    """
    Main Function
    """
    tuple = ("one", "two", "three", "four", "five", "six", "seven", "eight",
             "nine", "ten")
    list = ["one", "two", "three", "four", "five", "six", "seven", "eight",
            "nine", "ten"]
    dict = {
        "one": 1,
        "two": 2,
        "three": 3,
        "four": 4,
        "five": 5,
        "six": 6,
        "seven": 7,
        "eight": 8,
        "nine": 9,
        "ten": 10
    }

    for line in list:
        print(line.capitalize)

    while true:
        for line in tuple:
            pass

    if list[0]:
        sys.exit()

    print(list)
    print(dictionary)

def __main__ == "__main__":
    main()
